// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: vote_permission_service.proto

package vote_permission_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VotePermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *VotePermission) Reset() {
	*x = VotePermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vote_permission_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VotePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotePermission) ProtoMessage() {}

func (x *VotePermission) ProtoReflect() protoreflect.Message {
	mi := &file_vote_permission_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotePermission.ProtoReflect.Descriptor instead.
func (*VotePermission) Descriptor() ([]byte, []int) {
	return file_vote_permission_service_proto_rawDescGZIP(), []int{0}
}

func (x *VotePermission) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VotePermission) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetVotePermissionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VotePermissions []*VotePermission `protobuf:"bytes,1,rep,name=votePermissions,proto3" json:"votePermissions,omitempty"`
}

func (x *GetVotePermissionsResponse) Reset() {
	*x = GetVotePermissionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vote_permission_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVotePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVotePermissionsResponse) ProtoMessage() {}

func (x *GetVotePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vote_permission_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVotePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetVotePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_vote_permission_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetVotePermissionsResponse) GetVotePermissions() []*VotePermission {
	if x != nil {
		return x.VotePermissions
	}
	return nil
}

type RefreshVotePermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RefreshVotePermissionRequest) Reset() {
	*x = RefreshVotePermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vote_permission_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshVotePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVotePermissionRequest) ProtoMessage() {}

func (x *RefreshVotePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vote_permission_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVotePermissionRequest.ProtoReflect.Descriptor instead.
func (*RefreshVotePermissionRequest) Descriptor() ([]byte, []int) {
	return file_vote_permission_service_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshVotePermissionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RefreshVotePermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RefreshVotePermissionResponse) Reset() {
	*x = RefreshVotePermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vote_permission_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshVotePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVotePermissionResponse) ProtoMessage() {}

func (x *RefreshVotePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vote_permission_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVotePermissionResponse.ProtoReflect.Descriptor instead.
func (*RefreshVotePermissionResponse) Descriptor() ([]byte, []int) {
	return file_vote_permission_service_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshVotePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_vote_permission_service_proto protoreflect.FileDescriptor

var file_vote_permission_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x67, 0x6f, 0x76, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a,
	0x0e, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x22, 0x66, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x76, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x67, 0x6f, 0x76, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x6f, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x76, 0x6f, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x38, 0x0a, 0x1c,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x39, 0x0a, 0x1d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0xeb, 0x01, 0x0a, 0x15, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2a, 0x2e, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x67, 0x6f, 0x76, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f,
	0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x15, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x67, 0x6f, 0x76, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x67, 0x6f, 0x76, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1c, 0x5a, 0x1a, 0x67, 0x6f, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vote_permission_service_proto_rawDescOnce sync.Once
	file_vote_permission_service_proto_rawDescData = file_vote_permission_service_proto_rawDesc
)

func file_vote_permission_service_proto_rawDescGZIP() []byte {
	file_vote_permission_service_proto_rawDescOnce.Do(func() {
		file_vote_permission_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_vote_permission_service_proto_rawDescData)
	})
	return file_vote_permission_service_proto_rawDescData
}

var file_vote_permission_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vote_permission_service_proto_goTypes = []interface{}{
	(*VotePermission)(nil),                // 0: cosmosgov_grpc.VotePermission
	(*GetVotePermissionsResponse)(nil),    // 1: cosmosgov_grpc.GetVotePermissionsResponse
	(*RefreshVotePermissionRequest)(nil),  // 2: cosmosgov_grpc.RefreshVotePermissionRequest
	(*RefreshVotePermissionResponse)(nil), // 3: cosmosgov_grpc.RefreshVotePermissionResponse
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 5: google.protobuf.Empty
}
var file_vote_permission_service_proto_depIdxs = []int32{
	4, // 0: cosmosgov_grpc.VotePermission.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: cosmosgov_grpc.GetVotePermissionsResponse.votePermissions:type_name -> cosmosgov_grpc.VotePermission
	5, // 2: cosmosgov_grpc.VotePermissionService.GetVotePermissions:input_type -> google.protobuf.Empty
	2, // 3: cosmosgov_grpc.VotePermissionService.RefreshVotePermission:input_type -> cosmosgov_grpc.RefreshVotePermissionRequest
	1, // 4: cosmosgov_grpc.VotePermissionService.GetVotePermissions:output_type -> cosmosgov_grpc.GetVotePermissionsResponse
	3, // 5: cosmosgov_grpc.VotePermissionService.RefreshVotePermission:output_type -> cosmosgov_grpc.RefreshVotePermissionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vote_permission_service_proto_init() }
func file_vote_permission_service_proto_init() {
	if File_vote_permission_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vote_permission_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VotePermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vote_permission_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVotePermissionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vote_permission_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshVotePermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vote_permission_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshVotePermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vote_permission_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_permission_service_proto_goTypes,
		DependencyIndexes: file_vote_permission_service_proto_depIdxs,
		MessageInfos:      file_vote_permission_service_proto_msgTypes,
	}.Build()
	File_vote_permission_service_proto = out.File
	file_vote_permission_service_proto_rawDesc = nil
	file_vote_permission_service_proto_goTypes = nil
	file_vote_permission_service_proto_depIdxs = nil
}
